# Generated by Django 6.0.7 on 2026-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_postimage_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість дизлайків'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість лайків'),
        ),
    ]
