# Generated by Django 6.0.7 on 2026-08-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_dislikes_count_post_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
