<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-07-23 16:39
=======
# Generated by Django 6.0.7 on 2026-07-29 15:39
>>>>>>> 9252d2e2541eddd7772fa14580e417d85b75034c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
